### PR TITLE
ch(readme) update ReadMe

### PR DESCRIPTION
**Pull request by bbaime98**
### What does this PR do?
- update readme file
#### Description of Task to be completed?
- add descriptive instruction of how to use the endpoints
#### How should this be manually tested?
- check the Readme file
#### Questions:

### CODE REVIEW

**Review by Ntare22 — CHANGES_REQUESTED** [review]
Is there way we can automate setting up the database so that one cannot have to go through the sequelize commands?

**Review by Mnickii — CHANGES_REQUESTED** [review]
as @Ntare22 suggested, there should be scripts in out package.json for migrating and seeding our database

**Comment by bbaime98** [comment]
> as @Ntare22 suggested, there should be scripts in out package.json for migrating and seeding our database



> Is there way we can automate setting up the database so that one cannot have to go through the sequelize commands?

yeah that can be done. I will  add those instructions too.

**Comment by bbaime98** [comment]
> as @Ntare22 suggested, there should be scripts in out package.json for migrating and seeding our database

of course, those scripts are available. let me update  it.

**Comment by Mnickii** [comment]
please rebase this

**Comment by Mnickii** [comment]
Let's get done with this, detail the README with sufficient details to completely setup and run the project @bbaime98

**Comment by Mnickii** [comment]
rebase

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
